import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { fonts } from './fonts'
import './globals.css'
import { Provider } from './chakra_providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fonts.roboto.variable}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
